### ISSUE TITLE
🐛 Incomplete Example

### ISSUE THREAD

**Issue by burgholzer** [cda-tum/qecc#50]
### mqt.qecc version

latest

### OS

any

### Python version

any

### C++ compiler

any

### Additional environment information

N/A

### Description

The example file that is provided in the docs in the walkthrough section (https://qecc.readthedocs.io/en/latest/Installation.html#a-detailed-walk-through) is incomplete and does not work out of the box. It is missing the import of the library.

### Expected behavior

The example should be complete and executable without modifications.

### How to Reproduce

Copy the code from https://qecc.readthedocs.io/en/latest/Installation.html#a-detailed-walk-through and run the script.

**Comment by lucasberent** [comment]
#51
